### ISSUE TITLE
Post page Overview

### ISSUE THREAD

**Issue by meDracula** [meDracula/Pyshare#16]
# Post page overview Initial
The post page is the whole point of this website.
Here the user can see posts problems that others have posted.
Wait for #35 
## TODO
- [x] Display poster titles, created, username
- [x] Search text box for finding relevant post to title
- [x] Switch between search and latest result
> **NOTE** Due to no #39 or Tags develop this issue will have to be updated later on

* reference: https://stackoverflow.com/questions/tagged/python

## Time
* Estimated time: 03:00
* Completed time interval: 04:46
