### ISSUE TITLE
Python Mongo backend functions

### ISSUE THREAD

**Issue by meDracula** [meDracula/Pyshare#22]
# Functioner för frontend delen
Denna issues är till för att frontend och middleware att kunna lägga till functioner som behövs för att kunna nå data i databasen eller lägga till. 
> **NOTE** Detta kommer vara ett levenade issues(**DON'T close issue**)
## TODO
- [x] Create new user is a part of #25 
- [x] Add ResultList functions:
  - [x] return all search results
  - [x] return nth search results
- [x] Get users with kwargs instead of positional arguments
- [x] Kolla över sök optimeringar bland funktioner
- [x] Delete functions:
  - [x] Delete post
  - [x] Delete user

## Time
* Estimated time: 01:00
* Completed time interval: 00:18
