### ISSUE TITLE
Database schema

### ISSUE THREAD

**Issue by meDracula** [meDracula/Pyshare#26]
# Validation of Mongodb Schema
Although mongodb is meant to be flexible a agreed a upon schema 

## TODO
Being worked on now....
- [x] Schema
- [x] Performance testing/.explain():
  - [x] users
  - [x] posts
  - [x] text on post title
  - [x] post skip + limit .i.e iterate 10
- [x] Indexes:
  - [x] users
  - [x] post title
  - [x] post by datetime
  - [x] post skip + limit .i.e iterate 10
  - [x] text search on post title
- [x] Pattern:
  - [x] Schema version control
- [x] Uniqueness to decide schema fields
- [x] Think/Research query efficiency and ... optimization in general
- [x] Learn Validate schema

## Time
* Estimated time: 04:00
* Completed time interval:
