### ISSUE TITLE
Post

### ISSUE THREAD

**Issue by meDracula** [meDracula/Pyshare#30]
# Show a finsished Post
This issue is built on #35 and #16 
## TODO:
- [x] #16 <a href=  to Post
- [x] Title
- [x] Created
- [x] Description of problem
- [x] A discussion section:
  - [x] Allowing user to pose a quetion in the post
- [x] See solution code
- [x] A button to redirect to Solve it #31 

## Time
Estimated time: 05:00
Completed time interval: hh:mm

> **NOTE** More is probably needed so ask yourself what more would you the user want
