### ISSUE TITLE
Update and Deprecate the User Controller layer

### ISSUE THREAD

**Issue by meDracula** [meDracula/Pyshare#37]
# Upgrade the User layer functions
This will come from #26 
## TODO
- [x] Create a user login function with boolean return
- [x] get_account information function
- [x] Allow for either username or email to be pass in as argument
- [x] $or find with username or email
- [x] Deprecate:
  - [x] get_all_users
  - [x] verify_password
  - [x] verify_user

## Time
* Estimated time: 02:00
* Completed time interval: 02:40
