### ISSUE TITLE
create badges for users

### ISSUE THREAD

**Issue by meDracula** [meDracula/Pyshare#47]
# Badges
Badges are a social type deal to give users rewards for something. Badges will be the way to determine good user from bad due what badges a users have
## TODO
- [ ] Create a list of badges
- [ ] Have badges add to user in database
- [ ] Have badges shown in User Profile
