### ISSUE TITLE
Log out

### ISSUE THREAD

**Issue by meDracula** [meDracula/Pyshare#49]
# Log out
When a user is login there should be a option to log out
## TODO
- [x] Have log out only show when user is logged in
- [x] Log out user
- [x] Give the user some indication(flash or alert )  to know they just logged out

## Time
Estimated time: 00:30
Completed time interval: 01:00
