### ISSUE TITLE
Create a write new Post problem page

### ISSUE THREAD

**Issue by meDracula** [meDracula/Pyshare#50]
# new Post problem
A page for a user to create a new post problem.
## TODO
- [x] Page for writing post & redirecting to
- [x]  have writing new post show up to login users
- [x] Create form for writing post
- [x] Have post add to database and post collection
- [x] Pluming the post

## Time
Estimated time: 04:00
Completed time interval: hh:mm
