### ISSUE TITLE
Dockerizing Init

### ISSUE THREAD

**Issue by meDracula** [meDracula/Pyshare#57]
#  Setup the new docker environment

## TODO
- [x] Remove/Clean up port forwarding
- [x] Multi-stage Pyshare_Flask Container
- [x] Create Mongo Volume Dockerfile

## Time
Estimated time: 10:00
Completed time interval: 25:00
