### ISSUE TITLE
Build Docker Testit container

### ISSUE THREAD

**Issue by meDracula** [meDracula/Pyshare#76]
# Container Testit 
Testit is the container running user submitted test code
## TODO
- [x] Rewrite Controller code_controller to move user submitted code to pyshare_testit contianer
- [x] Write a continouse running script waiting TCP connection from flask container:
  - [x] Revc data/test code
  - [x] RUN test code in container
  - [x] Send back the status of green(code works) or red(code dosen't work)

## Time
Estimated time: 03:00
Completed time interval: 06:00
